version: "3.5"

services:
  php:
    build:
      context: ./docker/php
      dockerfile: Dockerfile
    volumes:
      - .:/var/www/blog

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - .:/var/www/blog
      - ./docker/nginx/blog.conf:/etc/nginx/conf.d/blog.conf
    depends_on:
      - php

  # mysql:
  #   image: cytopia/mysql-5.6
  #   restart: always
  #   environment:
  #     MYSQL_ROOT_PASSWORD: root
  #     MYSQL_GENERAL_LOG: 1
  #     MYSQL_SOCKET_DIR: /var/sock/mysqld
  #   ports:
  #     - "3306:3306"
  #   volumes:
  #     - ./docker/mysql/socket/:/var/sock/mysqld
  #     - ./docker/mysql/data/:/var/lib/mysql/data
  #     - ./docker/mysql/databases/:/tmp/databases
  #     - .:/var/www/gateway

  mysql:
    image: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      USER: root
      PASSWORD: root
    ports:
      - "3306:3306"
    volumes:
      - ./docker/mysql/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d


  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    ports:
      - "8080:80"
    environment:
      MYSQL_ROOT_PASSWORD: root
      PMA_USER: root
      PMA_PASSWORD: root
      PMA_HOSTS: mysql
    depends_on:
      - mysql